vala-lang/vala-www

LICENSE
LICENSE.md

Using the full text, GitHub is able to detect it and display it in the right panel :)

use full text for license

---

LICENSE
LICENSE.md
templates/base.html
templates/macros/body.html
templates/partials/footer.html

This PR (as the comment on one of the commits says) closes #27.

Change footer from a macro to a partial

---

sass/css/_base.scss
sass/css/components/_header-nav.scss
static/js/base.js
static/js/navbar.js
templates/base.html
templates/index.html

Use lighter Text color in light theme

---

sass/css/_base.scss

Fix overflow in blog posts

---

sass/css/_base.scss

changed h1 font weight to 300

---

sass/css/_base.scss

Fix bypass block contrast

---

sass/css/components/_header-nav.scss

Video of slowed original and fixed version:
https://user-images.githubusercontent.com/71781857/169107324-b5707787-9ad9-432c-a053-2f98c317985f.mp4

Fix hamburger icon transition

---

sass/css/components/_header-nav.scss
templates/macros/body.html

closes #67 
+ Prettier formating

Add "Get Started" button styling

---

sass/css/_base.scss
sass/css/components/_feature.scss
sass/css/components/_header-nav.scss
sass/css/index.scss

- Fix get started button overflow
- Set base font. Increase breakpoints
Fixes #70

fix overflowing get started link

---

content/about/index.md
templates/partials/footer.html
templates/shortcodes/predefined_cta_stack.html

- Updated about page with feedback from #1
- List selection of language feautures under "What is Vala?"
- Update footer to be specific about the website's source code
- Update footer to be specific about the website's source code

about page update

---

content/_index.md
content/about/index.md
content/blog/_index.md
content/blog/vala-0.56.md
templates/base.html
templates/blog-post.html
templates/blog.html
templates/index.html
templates/macros/head.html
templates/page.html

Open Graph meta tags now added to all existing templates

---

content/blog/vala-0.56.md
sass/css/_base.scss
sass/css/components/_header-nav.scss
sass/css/index.scss
sass/css/utils/_container.scss
templates/blog.html

- Container is now aware of safe areas by default
- Fixed home page layout
- Completely eliminate safe area overlap
- Reduce bottom padding in footer
- Improve spacing in Comunity section
- Footer updated to match horizontal container padding
- Fix formatting of in vala-0.56 release blog post

114 improve container

---

content/blog/vala-0.56.md
docs/3-pages.md
sass/css/blog-post.scss
sass/css/blog.scss
templates/blog-post.html
templates/blog.html
templates/index.html
templates/macros/blog.html
templates/macros/body.html
templates/macros/for-blog.html
templates/macros/head.html

- Update blog template with updated styling and extra data displayed
- Add author to post previews in what's new section
- First blog post in list will not have a top margin
- Change the way blog post titles are set
- Update blog post template to show more use more page varibles
- Remove old blog post styling comments
Fixes #89 and fixes #90

Update blog templates

---

sass/css/_base.scss
sass/css/components/_cta.scss
sass/css/components/_header-nav.scss
sass/css/components/_post-preview.scss
sass/css/components/_showcase.scss

- All hover state styling also applies to focus state
- Override focus outline styling
- Handle focus outline styling for special cases
Closes #85

85 improve link focus states

---

templates/macros/body.html

Change GitLab link text from 'GitLab' to 'Source Code'

---

sass/css/components/_showcase.scss
static/icons/showcase/peek.svg

- Now using a CSS Grids for the showcase
- Remove peek "template" SVG title
Fixes #102

102 fix showcase grid spacing and centering issues

---

assets/code-sample.md

Fixes #117 
Let me know if someone has a better idea for example. I was thinking of working on a counter application which shows the number of times a button is clicked but I don't have the idea of the best practices to write Vala.

Updates code sample

---

templates/index.html
templates/partials/community.html
templates/partials/features.html
templates/partials/usages.html

Update "why vala?" section.
New "What can you build?" section.
Update "Community" section.
Update "Social Media" section.

Multiple updates

---

assets/code-sample.md
content/blog/vala-0.56.md

Removing the Line Numbers from the code for now.
We will add it back once zola updates.
Fixes #142

#142 Removed the Linenos

---

config.toml

Update Matrix URL

---

config.toml

Improvement of the French translation and some linguistic corrections

Improved French Translations

---

config.toml
content/_index.zh_CN.md
content/about/index.zh_CN.md
templates/macros/body.html

Add Simplified Chinese translation.

Simplified Chinese translation

---

.devcontainer.json
Dockerfile
docker-compose.yml

Docker Configuration

---

content/blog/valabot.md

I've created a blog post with some information about a coding AI fine-tuned on Vala. I believe it will be of interest to many in the Vala community.

ValaBot blog post

---

config.toml
templates/macros/body.html
templates/partials/versions.html

Replace Wiki links outside of blog with new docs site links
